#!/bin/bash -e

docker build -f $(PWD)/Dockerfile.certs -t minica:latest .
docker run --rm -it -v $(PWD)/certs:/certs minica:latest minica --domains "localhost,*.homelab.localhost" --ip-addresses "127.0.0.1"
