#!/bin/bash -e

rm -rf ssh-gitserver
rm -rf ssh-keys

script_dir=$(realpath $(dirname "$0"))

echo "Generating Host Keys"
docker run --rm -it \
    -v ${script_dir}/ssh-gitserver:/etc/ssh \
    ghcr.io/jkososki/certs:latest \
    ssh-keygen -A

echo "Generating User Keys"
docker run --rm -it \
    -v ${script_dir}/ssh-keys:/data \
    ghcr.io/jkososki/certs:latest \
    ssh-keygen -b 2048 -t rsa -f /data/id_rsa -q -N ""