#!/bin/bash -e

docker build -f $(PWD)/Dockerfile.certs -t minica:latest $(PWD)/bootstrap/
docker run --rm -it -v $(PWD)/certs:/certs minica:latest minica --domains "localhost,*.localhost" --ip-addresses "127.0.0.1"
