#!/bin/bash -e



CLUSTER_NAME=homelab
KIND_CONFIG=bootstrap/tmp.kind-config.yaml
cat bootstrap/kind-config.yaml | envsubst > $KIND_CONFIG

echo "Creating cluster $CLUSTER_NAME"
kind create cluster \
  -n $CLUSTER_NAME \
  --config $KIND_CONFIG

sleep 5
CURRENT_CLUSTER=$(kubectl config current-context)
if [ "$CURRENT_CLUSTER" != "$CLUSTER_NAME" ]; then
  echo "Switching to cluster kind-${CLUSTER_NAME}"
  kubectl config use-context kind-${CLUSTER_NAME}
fi

sleep 5
kubectl create namespace traefik
kubectl create secret tls \
  --namespace=traefik localhost-cert \
  --key=$(PWD)/bootstrap/certs/localhost/key.pem \
  --cert=$(PWD)/bootstrap/certs/localhost/cert.pem


cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: dynamic
  namespace: traefik
data:
  dynamic.toml: |
    # Dynamic configuration
    [[tls.certificates]]
    certFile = "/certs/tls.crt"
    keyFile = "/certs/tls.key"
EOF


helm upgrade --install traefik bootstrap/traefik-26.0.0.tgz \
  --namespace=traefik \
  --create-namespace \
  --wait \
  --values=bootstrap/traefik.values.yaml