---
# providers:
#   kubernetesCRD:
#     namespaces:
#       - default
#       - traefik
#   kubernetesIngress:
#     namespaces:
#       - default
#       - traefik

ports:
  traefik:
    expose: true
    nodePort: 32090
  web:
    nodePort: 32080
  websecure:
    nodePort: 32443

service:
  type: NodePort

ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik

volumes:
- name: localhost-cert
  mountPath: "/certs"
  type: secret
- name: dynamic
  mountPath: "/config"
  type: configMap

additionalArguments:
- --providers.file.filename=/config/dynamic.toml
- --accesslog=true
- --accessLog.fields.defaultMode="keep"
- --accessLog.fields.headers.defaultMode="keep"

logs:
  general:
    level: DEBUG