apiVersion: v1
kind: Service
metadata:
  name: gitd
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    {{- include "gitd.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22