apiVersion: v1
kind: Pod
metadata:
  name: prefer-3-gpu
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: gpu.nvidia.com/class
            operator: In
            values:
            - RTX_A6000
            - H100_NVLINK_80GB
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: gpu.nvidia.com/count
            operator: Gt
            values:
            - "2"
          - key: gpu.nvidia.com/class
            operator: In
            values: 
            - RTX_A6000
      - weight: 50
        preference:
          matchExpressions:
          - key: gpu.nvidia.com/class
            operator: In
            values:
            - H100_NVLINK_80GB
  containers:
  - name: with-node-affinity
    image: registry.k8s.io/pause:2.0