name: Publish Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      image:
        type: choice
        description: 'Docker image to publish'
        options:
        - docker/certs
        - docker/gitserver

env:
  REGISTRY: ghcr.io

jobs:
  get-builds:
    runs-on: ubuntu-22.04
    name: Get Builds
    outputs:
      publish_list: ${{ steps.get-df.outputs.publish_list }}
      publish_count: ${{ steps.get-df.outputs.publish_count }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Get Changes
      id: get-diff
      if: github.event_name == 'push'
      run: |
        diff=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | jq -R -s -c 'split("\n")[:-1]')
        echo "CHANGES=$diff" >> $GITHUB_OUTPUT
    - name: Get Dockerfiles
      id: get-df
      env:
        CHANGES: ${{ steps.get-diff.outputs.CHANGES }}
      shell: python
      run: |
        import os
        import json
        from pathlib import Path
        import yaml

        if os.getenv('CHANGES'):
          changes = json.loads(os.getenv('CHANGES'))
        else:
          changes = ['${{ inputs.image }}']

        # Get all Images in the change list
        modified_images = set()
        for df in list(Path('.').rglob('Dockerfile')):
          for change in changes:
            if change.startswith(str(df.parent)):
              modified_images.add(df)

        publish_list = [
          {"path": str(df.parent), "image": str(Path(*df.parent.parts([2:])))}
          for df in list(modified_images)
        ]

        print("publish_list:  ", json.dumps(publish_list, indent=2))
        with open(os.environ['GITHUB_OUTPUT'], 'a') as f_out:
          f_out.write(f'publish_list={json.dumps(publish_list)}\n')
          f_out.write(f'publish_count={len(publish_list)}\n')

        with open(os.environ['GITHUB_STEP_SUMMARY'], 'a') as f_out:
          f_out.write('# Images to Publish\n')
          if len(publish_list) > 0:
            for image in publish_list:
              f_out.write(f'- {image}\n')
          else: 
            f_out.write('No images to publish\n')

  publish-images:
    runs-on: ubuntu-22.04
    name: ${{ matrix.image }}
    if: ${{ needs.get-builds.outputs.publish_count > 0 }}
    permissions:
      packages: write
    needs: 
    - get-builds
    strategy:
      matrix: ${{ fromJson(needs.get-builds.outputs.publish_list) }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ${{ env.REGISTRY }}
    - name: Build and Push
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.path }}
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.image }}:${{ github.sha }}
          ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.image }}:latest