configs:
  cm:
    url: https://argocd.homelab.localhost:8443
  params:
    server.insecure: true


repoServer:
  volumes:
  - name: app-repo
    hostPath:
      path: /app-repo
      type: Directory
  volumeMounts:
  - mountPath: /app-repo
    name: app-repo
    readOnly: true

extraObjects:
- apiVersion: traefik.containo.us/v1alpha1
  kind: IngressRoute
  metadata:
    name: argocd
    namespace: argocd
  spec:
    entryPoints:
    - websecure
    routes:
    - match: Host(`argocd.homelab.localhost`)
      kind: Rule
      services:
      - name: argocd-server
        port: 80
    tls: {}